version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-latest
  commands:
    - mamba install -c conda-forge -c nodefaults pixi
    - pixi run -e docs postinstall
    - pixi run -e docs docs-build
    - pixi run -e docs readthedocs
formats:
  - pdf
