version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-latest
  commands:
    - mamba install -c conda-forge -c nodefaults pixi
    - pixi install
    - pixi run docs
    - pixi run readthedocs
formats:
- pdf

