name: pytest
description: installs package, runs pytest and creates coverage report.

inputs:
  backend:
    description: which database backend to use
    required: false
  args:
    description: arguments that are passed to pytest, e.g. "-k filter" or "tests/integration"
    required: false

runs:
  using: composite
  steps:
    - name: Run Integration Tests
      shell: bash -l {0}
      run: |
        flit install -s
        if [[ "${{ inputs.backend }}" != "" ]]; then
          pytest --cov=datajudge --cov-report=xml --cov-append --backend=${{ inputs.backend }} ${{ inputs.args }}
        else
          pytest --cov=datajudge --cov-report=xml --cov-append ${{ inputs.args }}
        fi
    - name: Generate code coverage report
      uses: codecov/codecov-action@v3.1.3
      with:
        file: ./coverage.xml
